name: Build binaries

on: [push, pull_request]

jobs:
  build_macos:
    name: Build macOS binary
    runs-on: macos-11
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
#      - name: Build
#        run: |
#          cd CPP/7zip/Bundles/Alone2
#          make -j -f ../../cmpl_mac_arm64.mak
      - name: Build double
        run: |
          cd CPP/7zip/Bundles/Alone2
          make -j -f ../../cmpl_mac.mak